export const ADMIN_JACKET_REQUEST = 'ADMIN_JACKET_REQUEST'
export const ADMIN_JACKET_SUCCESS = 'ADMIN_JACKET_SUCCESS'
export const ADMIN_JACKET_FAIL = 'ADMIN_JACKET_FAIL'


export const NEW_JACKET_REQUEST = 'NEW_JACKET_REQUEST'
export const NEW_JACKET_SUCCESS = 'NEW_JACKET_SUCCESS'
export const NEW_JACKET_FAIL = 'NEW_JACKET_FAIL'
export const NEW_JACKET_RESET = 'NEW_JACKET_RESET'


export const DELETE_JACKET_REQUEST = 'DELETE_JACKET_REQUEST'
export const DELETE_JACKET_SUCCESS = 'DELETE_JACKET_SUCCESS'
export const DELETE_JACKET_RESET = 'DELETE_JACKET_RESET'
export const DELETE_JACKET_FAIL = 'DELETE_JACKET_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'