export const ADMIN_JEANS_REQUEST = 'ADMIN_JEANS_REQUEST'
export const ADMIN_JEANS_SUCCESS = 'ADMIN_JEANS_SUCCESS'
export const ADMIN_JEANS_FAIL = 'ADMIN_JEANS_FAIL'


export const NEW_JEANS_REQUEST = 'NEW_JEANS_REQUEST'
export const NEW_JEANS_SUCCESS = 'NEW_JEANS_SUCCESS'
export const NEW_JEANS_FAIL = 'NEW_JEANS_FAIL'
export const NEW_JEANS_RESET = 'NEW_JEANS_RESET'


export const DELETE_JEANS_REQUEST = 'DELETE_JEANS_REQUEST'
export const DELETE_JEANS_SUCCESS = 'DELETE_JEANS_SUCCESS'
export const DELETE_JEANS_RESET = 'DELETE_JEANS_RESET'
export const DELETE_JEANS_FAIL = 'DELETE_JEANS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'