export const ADMIN_KURTA_REQUEST = 'ADMIN_KURTA_REQUEST'
export const ADMIN_KURTA_SUCCESS = 'ADMIN_KURTA_SUCCESS'
export const ADMIN_KURTA_FAIL = 'ADMIN_KURTA_FAIL'


export const NEW_KURTA_REQUEST = 'NEW_KURTA_REQUEST'
export const NEW_KURTA_SUCCESS = 'NEW_KURTA_SUCCESS'
export const NEW_KURTA_FAIL = 'NEW_KURTA_FAIL'
export const NEW_KURTA_RESET = 'NEW_KURTA_RESET'


export const DELETE_KURTA_REQUEST = 'DELETE_KURTA_REQUEST'
export const DELETE_KURTA_SUCCESS = 'DELETE_KURTA_SUCCESS'
export const DELETE_KURTA_RESET = 'DELETE_KURTA_RESET'
export const DELETE_KURTA_FAIL = 'DELETE_KURTA_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'