export const ADMIN_SHIRT_REQUEST = 'ADMIN_SHIRT_REQUEST'
export const ADMIN_SHIRT_SUCCESS = 'ADMIN_SHIRT_SUCCESS'
export const ADMIN_SHIRT_FAIL = 'ADMIN_SHIRT_FAIL'


export const NEW_SHIRT_REQUEST = 'NEW_SHIRT_REQUEST'
export const NEW_SHIRT_SUCCESS = 'NEW_SHIRT_SUCCESS'
export const NEW_SHIRT_FAIL = 'NEW_SHIRT_FAIL'
export const NEW_SHIRT_RESET = 'NEW_SHIRT_RESET'


export const DELETE_SHIRT_REQUEST = 'DELETE_SHIRT_REQUEST'
export const DELETE_SHIRT_SUCCESS = 'DELETE_SHIRT_SUCCESS'
export const DELETE_SHIRT_RESET = 'DELETE_SHIRT_RESET'
export const DELETE_SHIRT_FAIL = 'DELETE_SHIRT_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'