export const ADMIN_TSHIRT_REQUEST = 'ADMIN_TSHIRT_REQUEST'
export const ADMIN_TSHIRT_SUCCESS = 'ADMIN_TSHIRT_SUCCESS'
export const ADMIN_TSHIRT_FAIL = 'ADMIN_TSHIRT_FAIL'


export const NEW_TSHIRT_REQUEST = 'NEW_TSHIRT_REQUEST'
export const NEW_TSHIRT_SUCCESS = 'NEW_TSHIRT_SUCCESS'
export const NEW_TSHIRT_FAIL = 'NEW_TSHIRT_FAIL'
export const NEW_TSHIRT_RESET = 'NEW_TSHIRT_RESET'


export const DELETE_TSHIRT_REQUEST = 'DELETE_TSHIRT_REQUEST'
export const DELETE_TSHIRT_SUCCESS = 'DELETE_TSHIRT_SUCCESS'
export const DELETE_TSHIRT_RESET = 'DELETE_TSHIRT_RESET'
export const DELETE_TSHIRT_FAIL = 'DELETE_TSHIRT_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'